version: 2

# build job parameters as a template
defaults: &defaults
  working_directory: ~/app
  docker:
    # the Docker image with Cypress dependencies
    - image: cypress/base:8
      environment:
        ## this enables colors in the output
        TERM: xterm

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - app

  testA:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la cypress
      - run: ls -la cypress/integration
      - run:
          name: Running E2E tests A
          command: npm run testsuite-1
      - store_test_results:
          path: my-test-output1.xml
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots


  testB:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Running E2E tests B
          command: npm run testsuite-2
      - store_test_results:
          path: my-test-output2.xml
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - testA:
          requires:
            - build
      - testB:
          requires:
            - build
